POST http://localhost:8080/events 
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QzQGV4YW1wbGUuY29tIiwiZXhwIjoxNzEyNjQ0MjkxLCJ1c2VySWQiOjN9.YBYaGprwrEAEX3SjXPU287EsjVZ_SjKYoMjJrQ-PRB0

{
  "name": "The Best Event",
  "description": "This is the best event.",
  "location": "Jakarta",
  "dateTime": "2025-01-01T15:00:00.000Z"
} 