PUT http://localhost:8080/events/4 
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQGV4YW1wbGUuY29tIiwiZXhwIjoxNzEyNjQzNDE4LCJ1c2VySWQiOjJ9.EU_TSTjQkjIf3yX2pfiaHE46SxMdciCciuTjxclH7hY

{
  "name": "Test event",
  "description": "This is a better test event.",
  "location": "Jakarta",
  "dateTime": "2025-01-01T15:00:00.000Z"
}